/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagement;

import java.sql.*;
import javax.swing.JOptionPane;
public class GPA extends javax.swing.JFrame {

    Connection con= null;
    Statement st= null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private String studentID;
    String studentName;
    String department;
    String grade;
    String courseCode;
    private Student studentFrame; 
    
    public GPA(Student studentFrame, String studentID, String StudentName, String Department, String Grade) {
        setContentPane(new BackgroundPanel());
        initComponents();
        con= DBConnection.connectOnlineDB();
        setLocationRelativeTo(null);
        this.studentFrame =studentFrame;
        this.studentID = studentID;
        this.studentName = studentName;
        this.department = department;
        this.grade = grade;
        fetchGPAInfo(studentID);
    }
    private void fetchGPAInfo(String studentID) {
    try {
        String sql = "SELECT Notes.CourseCode, RegisterTeacher.CourseName, Notes.Midterm, Notes.Final, Notes.Project "
                   + "FROM Notes "
                   + "JOIN RegisterTeacher ON Notes.CourseCode = RegisterTeacher.CourseCode "
                   + "WHERE Notes.StudentID = ?";

        pst = con.prepareStatement(sql);
        pst.setString(1, studentID);
        rs = pst.executeQuery();

        double totalPoints = 0;
        int courseCount = 0;
        StringBuilder passedCourses = new StringBuilder("Passed Courses:\n");
        StringBuilder failedCourses = new StringBuilder("Failed (FF) Courses:\n");

        while (rs.next()) {
            String code = rs.getString("CourseCode");
            String name = rs.getString("CourseName");
            int midterm = rs.getInt("Midterm");
            int fin = rs.getInt("Final");
            int project = rs.getInt("Project");

            String letter = calculateLetterGrade(midterm, fin, project);
            double point = convertToPoint(letter);

            totalPoints += point;
            courseCount++;

            if (!letter.equals("FF")) {
                passedCourses.append(code + " - " + name + " --> " + letter + "\n");
            } else {
                failedCourses.append(code + " - " + name + " --> " + letter + "\n");
            }
        }

        double gpa = courseCount > 0 ? totalPoints / courseCount : 0.0;

        GPA.setText(String.format("GPA: %.2f\n\n", gpa) +
                    passedCourses.toString() + "\n" + failedCourses.toString());

    } catch (Exception e) {
        GPA.setText("Error calculating GPA: " + e.getMessage());
        e.printStackTrace();
    }
}
    private String calculateLetterGrade(int midterm, int finalExam, int project) {
    double average = (midterm * 0.3) + (project * 0.2) + (finalExam * 0.5);
    if (average >= 90) return "AA";
    else if (average >= 85) return "BA";
    else if (average >= 75) return "BB";
    else if (average >= 65) return "CB";
    else if (average >= 55) return "CC";
    else if (average >= 50) return "DC";
    else if (average >= 45) return "DD";
    else return "FF";
}

    private double convertToPoint(String letter) {
    switch (letter) {
        case "AA": return 4.0;
        case "BA": return 3.5;
        case "BB": return 3.0;
        case "CB": return 2.5;
        case "CC": return 2.0;
        case "DC": return 1.5;
        case "DD": return 1.0;
        default: return 0.0; // FF
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        GPA = new javax.swing.JTextArea();
        Quit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GPA.setColumns(20);
        GPA.setRows(5);
        GPA.setMaximumSize(new java.awt.Dimension(13, 20));
        jScrollPane1.setViewportView(GPA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 16, 330, 220));

        Quit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        getContentPane().add(Quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 251, 120, 40));

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 251, 120, 40));

        jPanel1.setBackground(new java.awt.Color(33, 136, 196));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 96, 154), 5));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 450));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_QuitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        studentFrame.setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextArea GPA;
    private javax.swing.JButton Quit;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
