/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagement;

import java.sql.*;
import javax.swing.JOptionPane;
public class Student extends javax.swing.JFrame {

    Connection con= null;
    Statement st= null;
    PreparedStatement pst = null;
    ResultSet rs = null;
   
    private String studentID;
    String studentName;
    String department;
    String grade;
    String courseCode;
    
    
    
    public Student(String StudentID, String StudentName, String Department, String Grade) {
        setContentPane(new BackgroundPanel());
        initComponents();
        con= DBConnection.connectOnlineDB();
        setLocationRelativeTo(null);
        
        this.studentID=StudentID;
        this.studentName=StudentName;
        this.department=Department;
        this.grade=Grade;
        
        Result.setText("ID: " + StudentID+ "\n" + "Name: " + StudentName + "\n" +"Department: " + Department + "\n" +"Grade: " + Grade);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        ViewNotes = new javax.swing.JButton();
        ViewTranscript = new javax.swing.JButton();
        CalculateGPA = new javax.swing.JButton();
        Courses = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Result = new javax.swing.JTextArea();
        ViewNote = new javax.swing.JButton();
        Transcript = new javax.swing.JButton();
        ViewMessages = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jButton1.setText("Show student information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        ViewNotes.setText("View notes");
        ViewNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewNotesActionPerformed(evt);
            }
        });

        ViewTranscript.setText("View transcript");

        CalculateGPA.setText("Calculate GPA");

        Courses.setText("Courses");
        Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        getContentPane().add(Quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 90, 40));

        Result.setColumns(20);
        Result.setRows(5);
        jScrollPane1.setViewportView(Result);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 21, 328, 183));

        ViewNote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewNote.setText("View Notes");
        ViewNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewNoteActionPerformed(evt);
            }
        });
        getContentPane().add(ViewNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        Transcript.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Transcript.setText("Transcript");
        Transcript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranscriptActionPerformed(evt);
            }
        });
        getContentPane().add(Transcript, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        ViewMessages.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewMessages.setText("View Messages");
        ViewMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMessagesActionPerformed(evt);
            }
        });
        getContentPane().add(ViewMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 90, 40));

        jPanel1.setBackground(new java.awt.Color(33, 136, 196));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 96, 154), 5));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_QuitActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        
    }//GEN-LAST:event_HomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesActionPerformed
        
    }//GEN-LAST:event_CoursesActionPerformed

    private void ViewNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewNotesActionPerformed

    private void ViewNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewNoteActionPerformed
        new Notes(studentID, studentName, department, grade).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_ViewNoteActionPerformed

    private void TranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TranscriptActionPerformed
        new GPA(this, studentID, studentName, department, grade).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TranscriptActionPerformed

    private void ViewMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMessagesActionPerformed
        new ReceiveMessage(studentID, studentName, department, grade).setVisible(true);
           this.dispose();
    }//GEN-LAST:event_ViewMessagesActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton CalculateGPA;
    private javax.swing.JButton Courses;
    private javax.swing.JButton Home;
    private javax.swing.JButton Quit;
    private javax.swing.JTextArea Result;
    private javax.swing.JButton Transcript;
    private javax.swing.JButton ViewMessages;
    private javax.swing.JButton ViewNote;
    private javax.swing.JButton ViewNotes;
    private javax.swing.JButton ViewTranscript;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
