/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentmanagement;

import java.sql.*;
import javax.swing.JOptionPane;
public class TeacherNotes extends javax.swing.JFrame {

    Connection con= null;
    Statement st= null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public TeacherNotes(String name, String CourseCode) {
        setContentPane(new BackgroundPanel());
        initComponents();
        con= DBConnection.connectOnlineDB();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        DeleteNotes = new javax.swing.JButton();
        EnterNotes = new javax.swing.JButton();
        UpdateNotes = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        InsertNotes = new javax.swing.JButton();
        Message = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        DeleteNotes.setText("Delete Notes");
        DeleteNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteNotesActionPerformed(evt);
            }
        });

        EnterNotes.setText("Enter Notes");
        EnterNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNotesActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        UpdateNotes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateNotes.setText("Update Notes");
        UpdateNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateNotesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 100, 0, 0);
        getContentPane().add(UpdateNotes, gridBagConstraints);

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 30, 0, 0);
        getContentPane().add(Back, gridBagConstraints);

        Quit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        getContentPane().add(Quit, gridBagConstraints);

        InsertNotes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertNotes.setText("Insert Notes");
        InsertNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertNotesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 100, 0, 0);
        getContentPane().add(InsertNotes, gridBagConstraints);

        Message.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Message.setText("Message");
        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 111;
        gridBagConstraints.ipady = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 100, 0, 0);
        getContentPane().add(Message, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(33, 136, 196));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(18, 96, 154), 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 380;
        gridBagConstraints.ipady = 420;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterNotesActionPerformed

    private void DeleteNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteNotesActionPerformed

    private void UpdateNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateNotesActionPerformed
   
        int studentID = -1;
        while (true) {
            try {
                String input = JOptionPane.showInputDialog("Student ID:");
                if (input == null) {
                    JOptionPane.showMessageDialog(null, "Input cancelled.");
                    break;
                }
                if (!input.matches("\\d{9}")) {
                    JOptionPane.showMessageDialog(null, "Please enter a 9-digit numeric Student ID.");
                    continue;
                }
                studentID = Integer.parseInt(input);
                break;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid numeric Student ID.");
            }
        }

        int courseCode = -1;
        while (true) {
            try {
                String input = JOptionPane.showInputDialog("Course Code:");
                if (input == null) {
                    JOptionPane.showMessageDialog(null, "Input cancelled.");
                    break;
                }
                if (!input.matches("\\d{3}")) {
                    JOptionPane.showMessageDialog(null, "Please enter a 3-digit numeric Course Code.");
                    continue;
                }
                courseCode = Integer.parseInt(input);
                break;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid numeric Course Code.");
        }
        }
    int newMidterm = -1;
    while (true) {
    try {
        String input = JOptionPane.showInputDialog("Enter new Midterm:");
        if (input == null) {
            JOptionPane.showMessageDialog(null, "Input cancelled.");
            break;
        }
        if (!input.matches("\\d{1,3}")) {
            JOptionPane.showMessageDialog(null, "Please enter a number with 1 to 3 digits .");
            continue;
        }
         newMidterm = Integer.parseInt(input);
         
         if(newMidterm>100 && newMidterm<0){
            JOptionPane.showMessageDialog(null, "You entered invalid value.");
            break;
        }
         
             break;
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid numeric Midterm.");
     }
    }
    
    int newFinal = -1;
    while (true) {
    try {
        String input = JOptionPane.showInputDialog("Enter new Final:");
        if (input == null) {
            JOptionPane.showMessageDialog(null, "Input cancelled.");
            break;
        }
        if (!input.matches("\\d{1,3}")) {
            JOptionPane.showMessageDialog(null, "Please enter a number with 1 to 3 digits.");
            continue;
        }
        newFinal = Integer.parseInt(input);
        
        if(newFinal>100 && newFinal<0){
            JOptionPane.showMessageDialog(null, "You entered invalid value.");
            break;
        }
        
        break;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid numeric Final.");
     }
    }

    int newProject = -1;
    while (true) {
    try {
        String input = JOptionPane.showInputDialog("Enter new Project:");
        if (input == null) {
            JOptionPane.showMessageDialog(null, "Input cancelled.");
            break;
        }
        if (!input.matches("\\d{1,3}")) {
            JOptionPane.showMessageDialog(null, "Please enter a number with 1 to 3 digits.");
            continue;
        }
        newProject = Integer.parseInt(input);
        
        if(newProject>100 && newProject<0){
            JOptionPane.showMessageDialog(null, "You entered invalid value.");
            break;
        }
        break;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid numeric Project.");
     }
    }

    String calculatedLetter = calculateLetterGrade(newMidterm,newFinal,newProject);
 
        
        
    try {
        String sql3 = "UPDATE Notes SET Midterm = ?, Final = ?, Project = ?, LetterGrade = ? WHERE StudentID = ? AND CourseCode = ?";
        pst = con.prepareStatement(sql3);
        pst.setInt(1, newMidterm);
        pst.setInt(2, newFinal);
        pst.setInt(3, newProject);
        pst.setString(4, calculatedLetter);
        pst.setInt(5, studentID);
        pst.setInt(6, (courseCode));

        int updated = pst.executeUpdate();
        if (updated > 0) {
            JOptionPane.showMessageDialog(null, "Notes updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "No matching record found.");
        }

    }catch (NumberFormatException nfe){
    }
   
        catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_UpdateNotesActionPerformed

    private String calculateLetterGrade(int midterm, int finalExam, int project) {
        double average = (midterm * 0.3) + (project * 0.2) + (finalExam * 0.5);
        if (average >= 90) return "AA";
        else if (average >= 85) return "BA";
        else if (average >= 75) return "BB";
        else if (average >= 65) return "CB";
        else if (average >= 55) return "CC";
        else if (average >= 50) return "DC";
        else if (average >= 45) return "DD";
        else return "FF";
    }                     
    
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    
    
    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_QuitActionPerformed

    private void InsertNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertNotesActionPerformed
        
        String sql3 = "INSERT INTO Notes (StudentID, CourseCode, Midterm, Final, Project, LetterGrade) VALUES (?, ?, ?, ?, ?, ?)";

        
        int studentID = -1;
        while (true) {
            try {
                String input = JOptionPane.showInputDialog("Student ID:");
                if (input == null) {
                    JOptionPane.showMessageDialog(null, "Input cancelled.");
                    break;
                }
                if (!input.matches("\\d{9}")) {
                    JOptionPane.showMessageDialog(null, "Please enter a 9-digit numeric Student ID.");
                    continue;
                }
                studentID = Integer.parseInt(input);
                break;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid numeric Student ID.");
            }
        }

        int courseCode = -1;
        while (true) {
            try {
                String input = JOptionPane.showInputDialog("Course Code:");
                if (input == null) {
                    JOptionPane.showMessageDialog(null, "Input cancelled.");
                    break;
                }
                if (!input.matches("\\d{3}")) {
                    JOptionPane.showMessageDialog(null, "Please enter a 3-digit numeric Course Code.");
                    continue;
                }
                courseCode = Integer.parseInt(input);
                break;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter a valid numeric Course Code.");
        }
        }
    int newMidterm = -1;
    while (true) {
    try {
        String input = JOptionPane.showInputDialog("Enter new Midterm:");
        if (input == null) {
            JOptionPane.showMessageDialog(null, "Input cancelled.");
            break;
        }
        if (!input.matches("\\d{1,3}")) {
            JOptionPane.showMessageDialog(null, "Please enter a number with 1 to 3 digits .");
            continue;
        }
         newMidterm = Integer.parseInt(input);
         
         if(newMidterm>100 && newMidterm<0){
            JOptionPane.showMessageDialog(null, "You entered invalid value.");
            break;
        }
             break;
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid numeric Midterm.");
     }
    }
    
    int newFinal = -1;
    while (true) {
    try {
        String input = JOptionPane.showInputDialog("Enter new Final:");
        if (input == null) {
            JOptionPane.showMessageDialog(null, "Input cancelled.");
            break;
        }
        if (!input.matches("\\d{1,3}")) {
            JOptionPane.showMessageDialog(null, "Please enter a number with 1 to 3 digits.");
            continue;
        }
        
        newFinal = Integer.parseInt(input);
        
        if(newFinal>100 && newFinal<0){
            JOptionPane.showMessageDialog(null, "You entered invalid value.");
            break;
        }
        break;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid numeric Final.");
     }
    }

    int newProject = -1;
    while (true) {
    try {
        String input = JOptionPane.showInputDialog("Enter new Project:");
        if (input == null) {
            JOptionPane.showMessageDialog(null, "Input cancelled.");
            break;
        }
        if (!input.matches("\\d{1,3}")) {
            JOptionPane.showMessageDialog(null, "Please enter a number with 1 to 3 digits.");
            continue;
        }
        
        newProject = Integer.parseInt(input);
        
        
        if(newProject>100 && newProject<0){
            JOptionPane.showMessageDialog(null, "You entered invalid value.");
            break;
        }
        break;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid numeric Project.");
     }
    }

    String calculatedLetter = calculateLetterGrade(newMidterm,newFinal,newProject);
        
        
        
        
        try {
             

            
            String sql2 = "SELECT * FROM RegisterStudent WHERE StudentID = ?";
            PreparedStatement checkStudent = con.prepareStatement(sql2);
            checkStudent.setInt(1, studentID);
            ResultSet rsStudent = checkStudent.executeQuery();

            
            String sql4 = "SELECT * FROM RegisterTeacher WHERE CourseCode = ?";
            PreparedStatement checkCourse = con.prepareStatement(sql4);
            checkCourse.setInt(1, courseCode);
            ResultSet rsCourse = checkCourse.executeQuery();

            if (rsStudent.next() && rsCourse.next()) {
                
                String sqlInsert = "INSERT INTO Notes (StudentID, CourseCode, Midterm, Final, Project, LetterGrade) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(sql3);
                pst.setInt(1, studentID);
                pst.setInt(2, courseCode);
                pst.setInt(3, newMidterm);
                pst.setInt(4, newFinal);
                pst.setInt(5, newProject);
                pst.setString(6, calculatedLetter);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Note added successfully.");
            } else {
                String error = "";
                if (!rsStudent.next()) {
                    error += "Student ID not found. ";
                }
                if (!rsCourse.next()) {
                    error += "Course Code not found.";
                }
                JOptionPane.showMessageDialog(null, error.trim()); 
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                }

    }//GEN-LAST:event_InsertNotesActionPerformed

      
    
    
    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherMessage().setVisible(true);
            }
        });
       this.dispose();
    }//GEN-LAST:event_MessageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton DeleteNotes;
    private javax.swing.JButton EnterNotes;
    private javax.swing.JButton InsertNotes;
    private javax.swing.JButton Message;
    private javax.swing.JButton Quit;
    private javax.swing.JButton UpdateNotes;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
